# Generated by Django 3.2.6 on 2021-08-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0002_auto_20210823_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pending_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
