# Generated by Django 3.2.6 on 2021-08-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0003_alter_order_pending_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_product',
            new_name='orderproducts',
        ),
    ]
