# Generated by Django 3.2.6 on 2021-08-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0005_auto_20210824_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_payment',
            field=models.ManyToManyField(through='ordermanagement.OrderPayment', to='ordermanagement.Order'),
        ),
    ]
