# Generated by Django 3.2.6 on 2021-08-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0006_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime_payment',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de realización del pago'),
        ),
    ]
