# Generated by Django 3.2.6 on 2021-08-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='decription',
            new_name='description',
        ),
    ]
