# Generated by Django 3.2.6 on 2021-08-23 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
        ('ordermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_datetime', models.DateTimeField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordermanagement.order')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.stateshipment')),
            ],
        ),
    ]
